version: 0.2

phases:
  pre_build:
    commands:
      - |
          echo "Installing Node.js dependencies..."
          cd "$CODEBUILD_SRC_DIR/packages/web"
          npm ci

  build:
    commands:
      - |
          echo "Build started on $(date)"
          echo "Building React application..."
          cd "$CODEBUILD_SRC_DIR/packages/web"
          npm run build
          echo "Build completed successfully"

  post_build:
    commands:
      - |
          echo "Syncing static files to S3..."
          cd "$CODEBUILD_SRC_DIR/packages/web"
          aws s3 sync dist/ s3://${S3_BUCKET}/ --delete
          echo "Files synced to S3 bucket: ${S3_BUCKET}"
          
          echo "Invalidating CloudFront cache..."
          INVALIDATION_ID=$(aws cloudfront create-invalidation \
            --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} \
            --paths "/*" \
            --query 'Invalidation.Id' \
            --output text)
          echo "CloudFront invalidation created: $INVALIDATION_ID"

artifacts:
  files:
    - '**/*'
