version: 0.2

phases:
  pre_build:
    commands:
      - |
          echo "Installing Node.js dependencies..."
          cd "$CODEBUILD_SRC_DIR/packages/web"
          npm ci

  build:
    commands:
      - |
          echo "Build started on $(date)"
          echo "Building React application..."
          cd "$CODEBUILD_SRC_DIR/packages/web"
          # Clean previous build if it exists
          rm -rf dist
          # Build the application
          npm run build
          # Verify build output
          if [ ! -f "dist/index.html" ]; then
            echo "ERROR: index.html not found in dist directory"
            exit 1
          fi
          echo "Build completed successfully"
          echo "Build output structure:"
          find dist -type f | head -20

  post_build:
    commands:
      - |
          # Check if this is a deploy stage (staging or production)
          if [ -n "${DEPLOY_STAGE:-}" ]; then
            echo "=========================================="
            echo "DEPLOYMENT STAGE: ${DEPLOY_STAGE}"
            echo "=========================================="
            
            # Ensure we're in the correct directory
            cd "$CODEBUILD_SRC_DIR/packages/web"
            echo "Current working directory: $(pwd)"
            
            # Verify dist directory exists
            if [ ! -d "dist" ]; then
              echo "ERROR: dist directory not found. Build artifacts may be missing."
              exit 1
            fi
            
            # Verify index.html exists in dist
            if [ ! -f "dist/index.html" ]; then
              echo "ERROR: dist/index.html not found. Build artifacts may be incomplete."
              exit 1
            fi
            
            # Use absolute path for deployment
            DIST_PATH="$(pwd)/dist"
            echo "Source path: $DIST_PATH"
            echo "Target S3 bucket: ${S3_BUCKET}"
            
            # List contents for debugging
            echo "Contents of dist directory:"
            ls -la dist/
            echo "Number of files in dist: $(find dist -type f | wc -l)"
            
            # Sync to S3
            echo "Starting S3 sync from $DIST_PATH/ to s3://${S3_BUCKET}/"
            aws s3 sync "$DIST_PATH/" s3://${S3_BUCKET}/ --delete --exact-timestamps
            
            echo "Files synced to S3 bucket: ${S3_BUCKET}"
            
            # Verify what was synced to S3
            echo "Verifying S3 bucket contents (first 20 files):"
            aws s3 ls s3://${S3_BUCKET}/ --recursive | head -20
            
            # Count files in S3
            echo "Total files in S3 bucket: $(aws s3 ls s3://${S3_BUCKET}/ --recursive | wc -l)"
            
            # Invalidate CloudFront cache
            echo "Invalidating CloudFront cache..."
            INVALIDATION_ID=$(aws cloudfront create-invalidation \
              --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} \
              --paths "/*" \
              --query 'Invalidation.Id' \
              --output text)
            echo "CloudFront invalidation created: $INVALIDATION_ID"
            echo "Deployment to ${DEPLOY_STAGE} completed successfully!"
          else
            echo "=========================================="
            echo "BUILD STAGE: Artifacts created"
            echo "=========================================="
            echo "Build completed. Deployment will happen in deploy stage."
            echo "Dist directory ready with $(find packages/web/dist -type f 2>/dev/null | wc -l) files"
          fi

artifacts:
  base-directory: packages/web
  files:
    - 'dist/**/*'
