version: 0.2

phases:
  pre_build:
    commands:
      - |
          PIPELINE_PHASE="${PIPELINE_PHASE:-build}"
          echo "Pipeline phase: $PIPELINE_PHASE"
          
          # Read API Gateway URL from SSM Parameter Store
          echo "Reading API Gateway URL from SSM Parameter Store..."
          SSM_PARAM_NAME="/${PROJECT_NAME}/${ENVIRONMENT}/api_gateway/url"
          API_URL_FROM_SSM=$(aws ssm get-parameter \
            --name "$SSM_PARAM_NAME" \
            --region "$AWS_DEFAULT_REGION" \
            --query 'Parameter.Value' \
            --output text 2>/dev/null || echo "")
          
          if [ -n "$API_URL_FROM_SSM" ]; then
            export API_URL="$API_URL_FROM_SSM"
            echo "API_URL retrieved from SSM: $API_URL"
          else
            echo "WARNING: Could not retrieve API_URL from SSM parameter: $SSM_PARAM_NAME"
            echo "Falling back to environment variable if available."
          fi
          
          if [ "$PIPELINE_PHASE" = "build" ] || [ "$PIPELINE_PHASE" = "deploy" ]; then
            echo "Logging in to Amazon ECR..."
            aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
            export REPOSITORY_URI="$ECR_REPOSITORY"
            export COMMIT_HASH="$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)"
            export IMAGE_TAG="${COMMIT_HASH}-${CODEBUILD_BUILD_NUMBER}"
            echo "Image tag: $IMAGE_TAG"
          else
            echo "Health check phase - skipping ECR login."
          fi

  build:
    commands:
      - |
          PIPELINE_PHASE="${PIPELINE_PHASE:-build}"
          if [ "$PIPELINE_PHASE" = "build" ]; then
            echo "Build started on $(date)"
            echo "Building API Docker image..."
            cd "$CODEBUILD_SRC_DIR/packages/api"
            docker build -t "$REPOSITORY_URI:$IMAGE_TAG" .
            docker tag "$REPOSITORY_URI:$IMAGE_TAG" "$REPOSITORY_URI:latest"
          elif [ "$PIPELINE_PHASE" = "deploy" ]; then
            echo "Deploy phase: Updating Lambda function with new container image..."
            # Get image URI from build_output artifact
            IMAGE_FILE="$CODEBUILD_SRC_DIR_build_output/lambda-image.json"
            if [ ! -f "$IMAGE_FILE" ]; then
              IMAGE_FILE="$(find "$CODEBUILD_SRC_DIR" -name "lambda-image.json" | head -n 1)"
            fi
            if [ -f "$IMAGE_FILE" ]; then
              IMAGE_URI=$(python -c 'import json,sys; print(json.load(open(sys.argv[1]))["imageUri"])' "$IMAGE_FILE")
              echo "Updating Lambda function ${LAMBDA_FUNCTION_NAME} with image: $IMAGE_URI"
              aws lambda update-function-code \
                --function-name "${LAMBDA_FUNCTION_NAME}" \
                --image-uri "$IMAGE_URI" \
                --region "$AWS_DEFAULT_REGION"
              echo "Waiting for Lambda function update to complete..."
              aws lambda wait function-updated \
                --function-name "${LAMBDA_FUNCTION_NAME}" \
                --region "$AWS_DEFAULT_REGION"
              echo "Lambda function updated successfully."
            else
              echo "ERROR: lambda-image.json not found in build artifacts."
              exit 1
            fi
          else
            echo "Running API health check against ${API_URL}/health/ ..."
            if [ -z "${API_URL:-}" ]; then
              echo "API_URL environment variable is not set."
              exit 1
            fi
            # Check if API_URL is a placeholder
            if echo "$API_URL" | grep -qE "(abc123|EXAMPLE|placeholder|your-)" > /dev/null 2>&1; then
              echo "WARNING: API_URL appears to be a placeholder value: $API_URL"
              echo "Skipping health check. Please update api_gateway_url in terraform.tfvars with the actual API Gateway URL."
              echo "Health check skipped (placeholder URL detected)"
            else
              # Try health check with trailing slash (Django default)
              echo "Attempting health check against: ${API_URL}/health/"
              RESPONSE=$(curl -s -w "\n%{http_code}" -L --max-time 10 "${API_URL}/health/" 2>&1 || echo -e "\n000")
              BODY=$(echo "$RESPONSE" | head -n -1)
              STATUS_CODE=$(echo "$RESPONSE" | tail -n 1)
              
              echo "Response status: $STATUS_CODE"
              if [ -n "$BODY" ]; then
                echo "Response body: $BODY"
              fi
              
              if [ "$STATUS_CODE" = "200" ]; then
                echo "✓ Health check passed with status 200."
              else
                echo "✗ Health check failed with status ${STATUS_CODE}."
                
                # Try without trailing slash as fallback
                echo "Retrying without trailing slash: ${API_URL}/health"
                RESPONSE2=$(curl -s -w "\n%{http_code}" -L --max-time 10 "${API_URL}/health" 2>&1 || echo -e "\n000")
                BODY2=$(echo "$RESPONSE2" | head -n -1)
                STATUS_CODE2=$(echo "$RESPONSE2" | tail -n 1)
                
                echo "Response status: $STATUS_CODE2"
                if [ -n "$BODY2" ]; then
                  echo "Response body: $BODY2"
                fi
                
                if [ "$STATUS_CODE2" = "200" ]; then
                  echo "✓ Health check passed with status 200 (without trailing slash)."
                else
                  echo "✗ Both health check attempts failed."
                  echo "This may indicate the API is not yet deployed or there is a configuration issue."
                  exit 1
                fi
              fi
            fi
          fi

  post_build:
    commands:
      - |
          PIPELINE_PHASE="${PIPELINE_PHASE:-build}"
          cd "$CODEBUILD_SRC_DIR"
          if [ "$PIPELINE_PHASE" = "build" ]; then
            echo "Build completed on $(date)"
            echo "Pushing Docker image..."
            docker push "$REPOSITORY_URI:$IMAGE_TAG"
            docker push "$REPOSITORY_URI:latest"
            echo "Writing lambda image descriptor..."
            echo "{\"imageUri\": \"${REPOSITORY_URI}:${IMAGE_TAG}\"}" > lambda-image.json
            cat lambda-image.json
          else
            echo "Health check completed on $(date)"
            echo "{\"status\": \"ok\", \"checkedAt\": \"$(date +%Y-%m-%dT%H:%M:%SZ)\"}" > lambda-image.json
            cat lambda-image.json
          fi

artifacts:
  files:
    - lambda-image.json

