version: 0.2

phases:
  pre_build:
    commands:
      - |
          echo "Terraform deployment started on $(date)"
          echo "Environment: ${TF_VAR_environment:-staging}"
          echo "Ensuring Terraform is installed..."
          if ! command -v terraform >/dev/null 2>&1; then
            wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
            unzip terraform_1.6.0_linux_amd64.zip
            chmod +x terraform
            mv terraform /usr/local/bin/
          fi
          terraform version
      - |
          echo "Checking for lambda image URI..."
          IMAGE_FILE="$CODEBUILD_SRC_DIR/lambda-image.json"
          if [ ! -f "$IMAGE_FILE" ] && [ -n "${CODEBUILD_SRC_DIR_build_output:-}" ]; then
            IMAGE_FILE="$CODEBUILD_SRC_DIR_build_output/lambda-image.json"
          fi
          if [ -f "$IMAGE_FILE" ]; then
            echo "Discovered lambda-image.json artifact at $IMAGE_FILE"
            export TF_VAR_lambda_image_uri=$(python -c 'import json,sys; print(json.load(open(sys.argv[1]))["imageUri"])' "$IMAGE_FILE")
            echo "TF_VAR_lambda_image_uri set to $TF_VAR_lambda_image_uri"
          elif [ -n "${DEFAULT_LAMBDA_IMAGE_URI:-}" ]; then
            export TF_VAR_lambda_image_uri="$DEFAULT_LAMBDA_IMAGE_URI"
            echo "TF_VAR_lambda_image_uri set from DEFAULT_LAMBDA_IMAGE_URI: $TF_VAR_lambda_image_uri"
          else
            echo "Error: Neither lambda-image.json nor DEFAULT_LAMBDA_IMAGE_URI is available."
            exit 1
          fi

  build:
    commands:
      - |
          echo "Initializing Terraform..."
          cd "$CODEBUILD_SRC_DIR/ops/iac"
          terraform init
      - |
          echo "Running Terraform ${TF_ACTION}..."
          if [ "$TF_ACTION" = "plan" ]; then
            terraform plan -out=tfplan
          elif [ "$TF_ACTION" = "apply" ]; then
            if [ -f "tfplan" ]; then
              terraform apply -auto-approve tfplan
            else
              echo "Error: tfplan file not found. Run plan first."
              exit 1
            fi
          else
            echo "Error: TF_ACTION must be 'plan' or 'apply'"
            exit 1
          fi

  post_build:
    commands:
      - |
          echo "Terraform deployment completed on $(date)"
          cd "$CODEBUILD_SRC_DIR/ops/iac"
          terraform output -json > terraform-outputs.json 2>/dev/null || echo "No outputs available"

artifacts:
  files:
    - terraform-outputs.json
