version: 0.2

phases:
  pre_build:
    commands:
      - |
          echo "Terraform deployment started on $(date)"
          echo "Environment: $TF_VAR_environment"
          echo "Ensuring Terraform is installed..."
          if ! command -v terraform >/dev/null 2>&1; then
            wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
            unzip terraform_1.6.0_linux_amd64.zip
            chmod +x terraform
            mv terraform /usr/local/bin/
          fi
          terraform version
      - |
          IMAGE_FILE="$CODEBUILD_SRC_DIR/lambda-image.json"
          if [ ! -f "$IMAGE_FILE" ] && [ -n "${CODEBUILD_SRC_DIR_build_output:-}" ]; then
            IMAGE_FILE="$CODEBUILD_SRC_DIR_build_output/lambda-image.json"
          fi
          if [ -f "$IMAGE_FILE" ]; then
            echo "Discovered lambda-image.json artifact at $IMAGE_FILE, exporting TF_VAR_lambda_image_uri"
            export TF_VAR_lambda_image_uri=$(python -c 'import json,sys; print(json.load(open(sys.argv[1]))["imageUri"])' "$IMAGE_FILE")
            echo "TF_VAR_lambda_image_uri set to $TF_VAR_lambda_image_uri"
          else
            echo "Warning: lambda-image.json not found; Terraform will require lambda_image_uri from variables."
            if [ -z "${TF_VAR_lambda_image_uri:-}" ] && [ -n "${DEFAULT_LAMBDA_IMAGE_URI:-}" ]; then
              export TF_VAR_lambda_image_uri="$DEFAULT_LAMBDA_IMAGE_URI"
              echo "TF_VAR_lambda_image_uri set from DEFAULT_LAMBDA_IMAGE_URI environment variable."
            fi
          fi

  build:
    commands:
      - |
          echo "Initializing Terraform..."
          cd "$CODEBUILD_SRC_DIR/ops/iac"
          rm -f backend.tf
          terraform init

          if [ "$TF_ACTION" = "plan" ]; then
            echo "Running Terraform plan..."
            if [ -f "${TF_VAR_environment}.tfvars" ]; then
              terraform plan -out=tfplan -var-file="${TF_VAR_environment}.tfvars"
            else
              terraform plan -out=tfplan
            fi
          elif [ "$TF_ACTION" = "apply" ]; then
            echo "Applying Terraform configuration..."
            if [ -f "tfplan" ]; then
              terraform apply -auto-approve tfplan
            else
              echo "Error: tfplan file not found. Run plan first."
              exit 1
            fi
          else
            echo "Error: TF_ACTION must be 'plan' or 'apply'"
            exit 1
          fi

  post_build:
    commands:
      - |
          echo "Terraform deployment completed on $(date)"
          echo "Outputting Terraform outputs..."
          terraform output -json > terraform-outputs.json

artifacts:
  files:
    - terraform-outputs.json
