"""
Django settings for Habit_Tracker project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-kh6@x^%b42999#ii=hnc&dz4+j5giscrg@fh-8s4jo0@(i2ga2)')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS configuration
# For Lambda/API Gateway, we need to allow API Gateway domain
# Also allow CloudFront domain if provided
allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
elif os.environ.get('AWS_LAMBDA_FUNCTION_NAME'):
    # Running in Lambda - API Gateway doesn't send Host header Django expects
    # Set to empty list to disable ALLOWED_HOSTS check (security handled by API Gateway/CloudFront)
    # A middleware will handle the Host header validation
    ALLOWED_HOSTS = []  # Empty list disables the check
else:
    # Local development defaults
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'habit.apps.HabitConfig',
    'Users.apps.UsersConfig',
    'crispy_forms',
    'fontawesomefree',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'Habit_Tracker.middleware.AllowAllHostsMiddleware',  # Bypass ALLOWED_HOSTS for Lambda
    'Habit_Tracker.middleware.CorsMiddleware',  # Handle CORS headers
    'Habit_Tracker.middleware.StripStagePrefixMiddleware',  # Strip API Gateway stage prefix
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Habit_Tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Habit_Tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Use environment variables for Docker/Lambda, fall back to local_settings for local development
if os.environ.get('DB_HOST'):
    # Docker/Production/Lambda database configuration (PostgreSQL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'habit_tracker'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
            'HOST': os.environ.get('DB_HOST', 'db'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
    # Use reader endpoint for read replicas if available (optional)
    if os.environ.get('DB_READER_HOST'):
        DATABASES['default']['HOST'] = os.environ.get('DB_READER_HOST')
elif os.environ.get('AWS_LAMBDA_FUNCTION_NAME'):
    # Running in Lambda but DB_HOST not set - use a dummy database config
    # This allows Django to start even if database isn't configured yet
    # The actual database connection will fail, but Django won't crash on startup
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'habittracker'),
            'USER': os.environ.get('DB_USER', 'dbadmin'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
elif os.path.exists('local_settings.py'):
    from local_settings import DATABASES
else:
    try:
        from .local_settings import DATABASES
    except ImportError:
        # Fallback if local_settings doesn't exist
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = os.environ.get('STATIC_URL', 'habit/static/')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'bootstrap5'

LOGIN_REDIRECT_URL = 'habit-home'
LOGIN_URL = 'login'

# Redis Cache Configuration
if os.environ.get('REDIS_HOST'):
    # ElastiCache Serverless uses port 6379 with TLS enabled
    # The port will be provided by aws_config.py from the SSM parameter
    redis_port = os.environ.get('REDIS_PORT', '6379')
    redis_host = os.environ.get('REDIS_HOST', 'cache')
    
    # ElastiCache Serverless requires TLS
    if os.environ.get('REDIS_USE_TLS', 'false').lower() == 'true':
        # ElastiCache Serverless runs in cluster mode - must use database 0 (no /1)
        # Cluster mode doesn't support SELECT command for switching databases
        redis_location = f"rediss://{redis_host}:{redis_port}?ssl_cert_reqs=none"
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': redis_location,
            }
        }
    else:
        # Non-TLS Redis (local development) - can use database 1
        redis_location = f"redis://{redis_host}:{redis_port}/1"
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': redis_location,
            }
        }
    
    # Use Redis for session storage in serverless environment
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
else:
    # Fallback to local memory cache if Redis is not available
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# Session Configuration for Serverless/Lambda
# Sessions are stored in Redis if available, otherwise in database
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'  # Set to True if using HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'  # Allows cookies to be sent in cross-site requests
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request to extend expiry
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CSRF Configuration for Serverless/Lambda
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_AGE = 86400
CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript to access
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'  # Set to True if using HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else [
    'https://bardhi.devops.konitron.com',
    'https://d3dw2izdb09tes.cloudfront.net',
]
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF tokens

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

